[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
sea-orm = { version = "2.0.0-rc.10"}
serde = { version = "1.0.228", features = ["derive"] }